theme: "hugo-PaperMod"
baseURL: https://www.vohai.xyz
languageCode: en-us
title: Hai's blog
menu:
    main:
        - identifier: post
          name: Post
          url: /post
          weight: 1
        - identifier: Project
          name: Project
          url: /project
          weight: 2
        - identifier: Resume
          name: Resume
          url: /static/pdf/cv.pdf
          weight: 3
        - identifier: Github
          name: Github
          url: "https://github.com/vohai611"
          weight: 4
        - identifier: Email
          name: Email
          url: "mailto:hai835559@gmail.com"
          weight: 5
Params:
    defaultTheme: dark
    ShowReadingTime: true
    ShowToc: true
    ShowCodeCopyButtons: true
    ShowBreadCrumbs: true
    homeInfoParams:
         Title: "Welcome!"
         Content: >
              - Hi! I am a graduated student in Logistic, Operation and Supply chain management.
              
              - In my two year of master program, I found my interest on Data science and programming, especially, R programming language.
              
              - This is a website where I present all my personal project on data science and operation problen. All of this project are on github. So, if you have any question on my project, please open an github issues or write me an email. 
              
              - Thank you!
              
              - This blog using [blogdown](https://github.com/rstudio/blogdown), you can browse source code of this website on my github [repository](https://github.com/vohai611/haivo)
              
    socialIcons:
        - name: github
          url: "https://github.com/vohai611"
        - name: linkedin
          url: "linkedin.com/in/hai-vo-434a85220"
        - name: email
          url: "mailto: haingocvo96@gmail.com" 
        - name: RsS
          url: "index.xml"
markup:
  highlight:
    codeFences: true
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    noClasses: true
    style: 'nord'
    tabWidth: 4
  goldmark:
    renderer:
      unsafe: true
