theme: "hugo-PaperMod"
baseURL: https://vohai.xyz
languageCode: en-us
title: Hai's blog
menu:
    main:
        - identifier: post
          name: Post
          url: /post
          weight: 1
        - identifier: Project
          name: Project
          url: /project
          weight: 2
        - identifier: Resume
          name: Resume
          url: /static/pdf/cv.pdf
          weight: 3
        - identifier: Github
          name: Github
          url: "https://github.com/vohai611"
          weight: 4
        - identifier: Email
          name: Email
          url: "mailto:hai835559@gmail.com"
          weight: 5
Params:
    defaultTheme: dark
    ShowReadingTime: true
    ShowToc: true
    ShowCodeCopyButtons: true
    ShowBreadCrumbs: true
    homeInfoParams:
         Title: "Welcome!"
         Content: >
              - Hi! I am a graduated student in Logistic and Supply chain management.
              
              - In my two year of master program, I found my interest on Data science and programming
              
              - This is my personal blog about my personal project and also my random thought
              
              - You can found the source code of this blog on my github repository [here](https://github.com/vohai611/haivo)
              
markup:
  highlight:
    codeFences: true
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    noClasses: true
    style: 'nord'
    tabWidth: 4
  goldmark:
    renderer:
      unsafe: true
